### PR TITLE
Move deprecated code to deprecated package

### PR DESCRIPTION
**Pull request by jecisc**
This change introduce a Bloc-Deprecated package and moves the deprecated classes and methods to it. 

The purpose is to not polluate the packages with deprecated stuff and only keep them to let the users migrate their code. (I hope this helps to speed up a bit the navigation in P11 also)

### CODE REVIEW

**Comment by tinchodias** [comment]
Is this a recommended good practice for all projects?

**Comment by tinchodias** [comment]
I fixed the merge conflict, it was simple, but still I doubt about the PR. 

The problem I see is breaking certain modularity between packages... this new "Bloc-Deprecated" requires all other packages in the Baseline.

**Comment by jecisc** [comment]
There have been discussions about this. Some people do not like it. Some do.

Personally I like it because it allows to remove all deprecated code at once and not to flood core packages with deprecated code.

I like it especially in Bloc since the code browser in P11 is really slow because of the huge size of Bloc package and this makes the package lighter. 

But I get it if this does not please you and you just close the PR :)

**Comment by Ducasse** [comment]
I would remove the deprecated geometry class without deprecation.

**Comment by Ducasse** [comment]
And putting everything in a package produces a lot of baseline changes.

**Comment by tinchodias** [comment]
> I would remove the deprecated geometry class without deprecation.

I created: https://github.com/pharo-graphics/Bloc/issues/436

**Comment by tinchodias** [comment]
Okay I agree with Stef, so sorry Cyril I'm closing the PR

**Pull request closed without merging**
