### PR TITLE
Created a small Demo browser

### PR DESCRIPTION
**Pull request by Enzo-Demeulenaere**
Hello, 

I wanted to try and create a Demo Browser with Spec2. It aims to display some example classes you can browse and display their methods code while showing the graphical result in a Space nearby. Here's a screenshot : 

Capture d’écran 2023-11-03 à 13 52 26

The Demo Browser can be opened executing 
```smalltalk 
BlDemoPresenter new open
```

I think this could be a great addition to Bloc and I would have loved having this at the beginning to understand Bloc basics.

This is the very first iteration as it is my first project with Spec2 but I'm proud of it. Also I wanted to share it early so this could be improved in early development. 

For now it browses through `BlExampleTest` subclasses as I saw most of available examples inherits this class but many methods return objects that are not `BlElement` so for now, for those methods, the browser displays a small text (see below) 

Capture d’écran 2023-11-03 à 14 00 52
 
Here's a list of things that I know aren't working right now : 
- methods that require at least one argument (but if we later focus on example scripts this should not be a concern)
- animations (due to a `repeats` message in some methods) 

There might be a lot of other problems in other methods but I suppose it is because I took all BlExampleTest subclasses, maybe create a package with only scripts or filter using pragmas could be a reasonable choice.

### CODE REVIEW

**Comment by tinchodias** [comment]
Great! Screenshot looks very nice. 
To add to baseline this new package, it should have as requirement the package Bloc-Spec2 and it uses SpBlSpaceInMorphPresenter.
I didn't try it yet. Do you prefer that we merge it first, or to add the baseline first?
Bah, or maybe it fits in other existing package, didn't really check that.

**Comment by Enzo-Demeulenaere** [comment]
I guess we could add it to Bloc-Spec2 package, I was just thinking maybe we should create a package just for the browser and classes that will hold the examples so a beginner to Bloc would see a package named "Bloc-Demo" and immediately understand

**Comment by tinchodias** [comment]
ok. I'm in for the new package. so you plan to add new classes? great

**Comment by Enzo-Demeulenaere** [comment]
I would first try to extract existing (and working) examples and add new ones with notions and concepts I understand enough

Feel free to add examples you know I'd be very glad ! 

Also any suggestion is obviously welcomed

**Pull request merged**
