### PR TITLE
TBlAligment evolution

### PR DESCRIPTION
**Pull request by labordep**
TBlAligment : add "is" testing methods for each states of the aligment + add unit tests

### CODE REVIEW

**Comment by tinchodias** [comment]
Thanks for the PR.
I suspect you want to propose it to be merged in the branch dev-1.0, not master.
Or am I wrong?
Because latest changes have been in that branch, and Toplo I think works with those changes in dev-1.0.

I think it wasn't a good idea from my side to keep master mostly for hotfixes to v1.0 and and use dev-1.0 for active development.

**Comment by tinchodias** [comment]
(the PR can be edit and change the target branch, no need to close and recreate the PR, I can do it if you want)

**Comment by labordep** [comment]
Hi @tinchodias, yes you right.
I would merge with the most recent branch, an I thinked that is the "main/master" branch.
Do you know why the check failed ? ("All checks have failed").

If you can edit the PR this is fine for me :) next time I prefer to don't start from the dev-1.0 branch by, personaliy, I think this is better to have the most recent code on the main/master branch. 

Thanks :)

**Comment by tinchodias** [comment]
I did edit. I don't know why the Github website shows that ton of files changed. I imagine you didn't meant that. This was before editing the target branch and also after changing it. Bah, i think before it was >800 files and now >700. Maybe some line-ending diff? I hope the diff by Iceberg is shorter. I will check and tell you.
thanks for the contribution!

**Comment by labordep** [comment]
Thanks Martin, sorry for the number of files. I have checked before if there was just only my modifications, but it is strange, but it's similar to a bug that I report here : https://github.com/pharo-project/pharo/issues/11972
If it is this bug, for the moment my only solution is to add a .gitattributes files into the repo.
:(

**Comment by labordep** [comment]
I think I will resend to you a PR without this problem. Don't lose time with this PR.

**Comment by tinchodias** [comment]
Nice! Iceberg shows the diff pretty good. Apparently there would be no problem if I merge PR. But files will have this linefeed issue and then the next commit on the repo with different linefeed will show again 800 files changes. The most important is that Iceberg understand the diff well... but if you say that you can re-commit with the issue fixed, then okay. 

Alternatively, probably we can reconstruct the change like this: On this UI, press on "Merge into the image" and then commit and push it again.


Screenshot 2022-12-20 at 11 14 58

**Comment by labordep** [comment]
Ok @tinchodias, I will try to send a new PR :) 
It will be with a new .gitattributes file to fix EOF encoding problem.

**Pull request closed without merging**
