### PR TITLE
Remove BLCursor in favor of Cursor

### PR DESCRIPTION
**Pull request by jecisc**
This change removes the while hierarchy of BLCursor to use the Cursor class instead. 

All subclasses were returning a form from the Cursor class and it was unused.

This should be more efficient since it will not recreate a form all the time but use a saved instance.

### CODE REVIEW

**Comment by jecisc** [comment]
I am not sure how the change broke the tests

**Comment by plantec** [comment]
thanks !

**Comment by tinchodias** [comment]
Hi @jecisc, thanks. This change reminds me to another around keyboard: there was Bl* that duplicated/wrapped the ones in Pharo. I agree if there is no need that we can directly use the Pharo ones. The class Cursor belongs to a Graphics* package and we might want to avoid the dependency but for now there dependency was there, so... you are not adding a dependency. I think it's okay.

In P11 the 2 failures are my fault. I will fix now. In P12, It's missing `Time millisecondsToRun:` I think @Ducasse removed it? I will check a replacement or removal.

**Comment by tinchodias** [comment]
Ah... who sends millisecondsToRun: and errors is smalltalk-ci, not Bloc:

```
Instance of Time class did not understand #millisecondsToRun:
Time class(Object)>>doesNotUnderstand: #millisecondsToRun:
SmalltalkCI class>>timeToRun:
SmalltalkCIPharo12 class(SmalltalkCI class)>>fold:on:block:
SmalltalkCIPharo12 class(SmalltalkCI class)>>fold:block:
SmalltalkCIPharo12 class(SmalltalkCI class)>>stage:id:block:
SmalltalkCIPharo12(SmalltalkCI)>>reportImageInfo
SmalltalkCIPharo12(SmalltalkCI)>>basicLoad
```

**Comment by jecisc** [comment]
The Smalltalk CI one is known and is been fixed IIRC. 

I was not sure about the P11 ones :) Thanks

**Comment by Ducasse** [comment]
Martin we will reintroduce the Time milliseconds: and deprecate it.

**Comment by tinchodias** [comment]
So, let's merge it

**Comment by plantec** [comment]
thanks.
now I have to fix Toplo :)

**Comment by Ducasse** [comment]
Excellent.

**Comment by jecisc** [comment]
> thanks. now I have to fix Toplo :)

I did not think about Toplo sorry.

I can take a look this week if you did not do it already

**Pull request merged**
