### PR TITLE
Clean up some task signals

### PR DESCRIPTION
**Pull request by tinchodias**
We are not listening these signals, and they make the code more difficult to comprehend. I'd remove them similarly what we did with telemetry in https://github.com/pharo-graphics/Bloc/pull/439

### CODE REVIEW

**Comment by tinchodias** [comment]
@plantec In my most recent commit, I simplified repeated task. I tried these uses:
* `ToExperiments class>>#example_rotationAnimation`
* `ToSandBox class>>#example_toLabelWithTime`
And Album examples, for the blinking cursor.

The example with fork works now

**Comment by plantec** [comment]
cool, I like all the cleaning.
"The example with fork works now", do you mean without BlTaskAction use ?

**Comment by tinchodias** [comment]
> cool, I like all the cleaning. "The example with fork works now", do you mean without BlTaskAction use ?

yes, without need of BlTaskAction. However, I think its better to use BlTaskAction.

**Comment by tinchodias** [comment]
This closes #449

**Pull request merged**
