### PR TITLE
Remove gesture and touch processors and events

### PR DESCRIPTION
**Pull request by tinchodias**
Related to issue #224

### CODE REVIEW

**Comment by tinchodias** [comment]
@plantec @labordep 
Are you against removing this code?
I prefer to ask before merging, for the case.

**Comment by labordep** [comment]
No problem, we will need to work on a great touch layer after !

**Review by plantec — APPROVED** [review]

**Comment by plantec** [comment]
approved :)

**Comment by plantec** [comment]
I think OnBloc don't have these classes

**Comment by tinchodias** [comment]
In https://github.com/plantec/OnBloc/commit/62dcad04daacd4228b42b8296abba5ebadfc1f3f I removed the space's inst vars.

**Pull request merged**
