### PR TITLE
Improvement in linear gradient with arbitrary angle [WIP]

### PR DESCRIPTION
**Pull request by tinchodias**
I consider it work in progress, but already much better than previous situation.

See: #270

### CODE REVIEW

**Comment by tinchodias** [comment]
A rendering test is needed

**Comment by tinchodias** [comment]
demo:

https://github.com/pharo-graphics/Bloc/assets/3044265/0c2b8f65-fbf0-4b7e-8ef7-a5960ca3395a



```smalltalk 
a := BlElement new
	size: 800 @ 300;
	yourself.

a forceLayout.
aSpace := BlSpace new.
aSpace
	addChild: a;
	extent: a size;
	show.
	
a addAnimation: 
    (BlNumberTransition new
			from: 0.0;
			to: Float twoPi;
			duration: 6 seconds;
			onStepDo: [ :t |
				| start end gradient |
				start := 0.5 asPoint.
				end := t cos @ t sin.
				gradient :=
					BlLinearGradientPaint new
						stops: {
							0.0 -> Color red.
							1.0 -> Color blue };
						start: start;
						end: end;
						yourself.
				a background: gradient ];
			yourself).

```

**Comment by tinchodias** [comment]
Interactive demo (move the cursor over the space):

```smalltalk
a := BlElement new
	size: 800 @ 400;
	yourself.
a forceLayout.

b := BlElement new
	background: Color black;
	size: 20 asPoint;
	position: a bounds center - 10;
	geometry: BlCircleGeometry new;
	yourself.

aSpace := BlSpace new.
aSpace
	addChild: a;
	addChild: b;
	extent: a size;
	show.
	
a when: BlMouseMoveEvent do: [ :evt |
	| direction gradient |
	direction := (evt position - a bounds center) normalized.
	gradient :=
		BlLinearGradientPaint new
			stops: {
				0.0 -> Color red.
				1.0 -> Color green };
			start: 0 asPoint;
			end: direction;
			yourself.
	a background: gradient ].
```

**Comment by tinchodias** [comment]
This thread in w3c mailing list in 2011 shows discussion about how to render the gradients when they are not exactly horizontal or vertical. 
https://lists.w3.org/Archives/Public/www-style/2011Jul/0265.html

IIUC, this PR makes our gradient work as the author called "normal", but CSS makes the "margin":

image

Any opinion @labordep @plantec on which one we need?

**Comment by tinchodias** [comment]
I'll try to explain it again. Look at a disadvantage of my implementation (that is what in the w3c thread the writer called "normal".) 

The label is the angle in degrees:

Screenshot 2023-07-10 at 20 32 22

A quite small variation in the angle makes the gradient quite a lot horizontal)

```smalltalk 
container :=
	BlElement new
		layout: BlLinearLayout vertical;
		constraintsDo: [ :c |
			c horizontal matchParent.
			c vertical matchParent ];
		yourself.

((0.0 to: 2.0 by: 0.2), {10. 20. 30. 40. 45}) do: [ :each | 
	| gradient start stop |
	end := 0 @ -1 rotateBy: each degreesToRadians about: 0@0.
	gradient := BlLinearGradientPaint new
		stops: {
			0.0 -> Color red.
			1.0 -> Color blue };
		start: 0@0;
		end: end;
		yourself.

	container addChild: (BlTextElement new
		text: ((each printShowingDecimalPlaces: 1) asRopedText
			foreground: Color white;
			fontSize: 25;
			yourself);
		border: (BlBorder paint: Color black width: 0.25);
		size: 200 @ 50;
		background: gradient;
		yourself) ].

container openInNewSpace
```

**Comment by tinchodias** [comment]
I think this example in the above mentioned w3c thread, compares a 45º gradient. First it is like in my implementation. It's 45º but looks almost like 90º. Instead, in CSS implementation (labeled as "magic"), a 45º gradient means go from top-left corner to right-bottom.

Screenshot 2023-07-10 at 20 38 42

**Comment by tinchodias** [comment]
I didn't emphasize a key fact in this PR: 

The start and stop points to define a `BlLinearGradientPaint` **only specify an angle**.

This is similar to CSS linear gradients, and that's why I compare (but in css you specify directly the angle, not a vector to then extract the angle from it...).

**Comment by tinchodias** [comment]
But the thing is that the rendering is strange:

Screenshot 2023-07-11 at 12 38 52

Left column, in Bloc+this PR. In right column, CSS.

**Comment by tinchodias** [comment]
As another implementation reference, the API in Roassal3 is different: the start and end points are in pixel units (center is 0@0)... you specify literally the points that Cairo uses to draw the linear gradient:

In this case, if you want to render a gradient in a rectangle of size 200@50, you tell the gradient to go from -100 @ -25 to 100 @  25, and this is analogous to tell 45º to CSS:

```smalltalk
paint := LinearGradientPaint fromArray: { 0 -> Color blue. 1 -> Color red }.
paint start: -100 @ -25.
paint stop:   100 @  25.

box := RSBox new.
box paint: paint.
box extent: 200 @ 50.

canvas := RSCanvas new.
canvas add: box.
canvas inspect
```

Screenshot 2023-07-11 at 12 55 43

Thanks Milton for the snippet.

**Comment by tinchodias** [comment]
Another demo of how current PR renders angles (in degrees):

1st column: 50@50. 2nd column: 200@50. 3rd column: 300@50.
Screenshot 2023-07-11 at 13 15 53

**Comment by Ducasse** [comment]
So what do we do with this PR?

**Pull request closed without merging**
