### PR TITLE
Enable coverage testing again

### PR DESCRIPTION
**Pull request by fniephaus**
Following up on https://github.com/hpi-swa/smalltalkCI/issues/236.

### CODE REVIEW

**Comment by fniephaus** [comment]
Looks like you didn't enable PR testing on Travis. Not sure why the AppVeyor build failed. Maybe restart?

**Comment by fniephaus** [comment]
@GlennCavarle any idea why the image could run out of memory? Looks like it's happening when trying to uninstall the coverage wrappers. Can you perform a coverage test locally? Is that working?

**Comment by GlennCavarle** [comment]
I just tried with fresh pharo image60+vm and coverage is working without issue.

**Comment by fniephaus** [comment]
Thanks. I'll have a look at it tomorrow...

**Comment by GlennCavarle** [comment]
Hi @fniephaus, do you have some ideas about what happening during coverage?
I made a test with SmalltalkCI locally and the problem seems to be the same, the image is no longer responding.

**Comment by fniephaus** [comment]
Hi @GlennCavarle,
Sorry for the delay. For which package did you run the coverage test locally?

**Comment by GlennCavarle** [comment]
I run the coverage for the Bloc package.
No log, no crash, probably the same infinite loop that leads to the out of memory on ci jobs.

**Comment by fniephaus** [comment]
Yes, I'm also getting the out of memory error locally. It looks like there is a problem with the coverage wrappers that are being installed. smalltalkCI tries to imitate the original TestRunner behavior, but I already found a bug. Nonetheless, I am getting a OOM error and it looks like too many classes are actually selected. I don't have more time to look into this today, but maybe tomorrow...

**Comment by GlennCavarle** [comment]
Ok, thanks @fniephaus.
I reverted temporarily your changes to make jobs working again.
Please let me know if you find a solution.

**Comment by fniephaus** [comment]
This has revealed a bug in smalltalkCI and the fix should be ready in a few hours.
I'll keep you posted.

**Comment by fniephaus** [comment]
Should work as soon as https://github.com/hpi-swa/smalltalkCI/pull/238 is merged.

**Comment by syrel** [comment]
Thanks @fniephaus ! :slightly_smiling_face:

**Pull request merged**
