### PR TITLE
Accessors for the current drag target

### PR DESCRIPTION
**Pull request by StephanEggermont**
Enabling things like

space := BlSpace new 
	extent: 800@600 ;
	yourself.
element := BlElement new 	
	size: 50@50;
	background: Color blue;
	addEventHandlerOn: BlDragStartEvent do: [ :evt | |drag handler|
			drag := BlElement new 	
				size: 50@50;
				background: Color random;
				yourself.
			handler := BlEventHandler on: BlDragEvent do: [ :evt2 |
				evt2 consumed: true.
				drag position: evt2 position ].
			drag addEventHandler: handler.
			drag addEventHandlerOn: BlDragEndEvent do: [ :evt2 |
				handler ifNotNil: [drag removeEventHandler: handler]. 
				handler := nil.
				evt2 consumed: true. ].
			space root addChild: drag.
			space mouseProcessor currentDragTarget: drag.
			evt consumed: true];
	yourself.
space root addChild:element.	
space show.

### CODE REVIEW

**Comment by syrel** [comment]
Thanks :)

I just have a few questions.
```
currentDragTarget: anObject
```

Can a current drag target be any object or a `BlElement`?
Does this method accept nils? (I try to put assertions [design by contract] in all setters that I touch)

**Comment by StephanEggermont** [comment]
I'm not quite sure this is the way to go. The direct usage of the mouseProcessor seems ugly.

**Comment by StephanEggermont** [comment]
Why is the appveyor build using a 60508 image?

**Comment by syrel** [comment]
> Why is the appveyor build using a 60508 image?

Nice question! Probably I didn't update Pharo version from 6.0 to 7.0 in appveyor config

**Comment by StephanEggermont** [comment]
No longer relevant

**Pull request closed without merging**
