### PR TITLE
461 ghost windows are not closing  system cleanup feature

### PR DESCRIPTION
**Pull request by labordep**

### CODE REVIEW

**Comment by labordep** [comment]
Linked to #461, previously merged in the bad branch (dev).

**Comment by labordep** [comment]
@tinchodias I cannot change the base branch from master to dev (it doesn't work). Can I push in master?

**Comment by tinchodias** [comment]
Its seems that dev already has this change.  Let me check

**Comment by tinchodias** [comment]
(I can't change the target, too)

https://github.com/pharo-graphics/Bloc/assets/3044265/060bdec0-9baa-480b-980e-f18002734e94

**Comment by tinchodias** [comment]
El jue, 7 mar 2024 a la(s) 3:58 p.m., Pierre Laborde (
***@***.***) escribió:

> @tinchodias <https://github.com/tinchodias>, I missunderstand, what is
> the branch to do the PR??
>

It was correct, the workflow should be new change -> dev -> master
And each baseline depends on master of its dependencies

**Comment by tinchodias** [comment]
@labordep @labordep I merged from dev to master in Alexandrie, Bloc and Album, but not Toplo because I don't know much of the latest changes in dev. I mean, if you consider it a good moment for doing the sync to master.

When I pushed the change to github, ithe PR was automatically closed. I didn't expect that but I think it's correct.

**Pull request merged**
