### PR TITLE
Mouse processor review for improved picking

### PR DESCRIPTION
**Pull request by plantec**

### CODE REVIEW

**Comment by tinchodias** [comment]
this fixed an issue reported by Pierre?

**Comment by plantec** [comment]
not specifically but the issue seems to be fixed

**Comment by plantec** [comment]
arrg no, it is still here
```
| space |
space := BlSpace new.
space root addEventFilterOn: BlClickEvent do: [ :event | event traceCr ].
space show 
```

**Comment by plantec** [comment]
I'll have a look at it

**Pull request merged**
