### PR TITLE
Import SVG: Restore basic support from BlocPac + Improvements

### PR DESCRIPTION
**Pull request by tinchodias**
BlocPac's code. Geometry refactored and improved.

### CODE REVIEW

**Comment by tinchodias** [comment]
```smalltalk
aSpace := BlSpace new
	extent: 1100@600;
	show;
	yourself.
aSpace root background: Color black.

{
'q t' -> 'M200,300 Q400,50 600,300 T1000,300'.
'pie slice' -> 'M300,200 h-150 a150,150 0 1,0 150,-150 z'.
'pie' -> 'M275,175 v-150 a150,150 0 0,0 -150,150 z'.
'arcs' -> 'M600,350 l 50,-25
           a25,25 -30 0,1 50,-25 l 50,-25
           a25,50 -30 0,1 50,-25 l 50,-25
           a25,75 -30 0,1 50,-25 l 50,-25
           a25,100 -30 0,1 50,-25 l 50,-25'.
'straight lines' -> 'M200,300 L400,50 L600,300
           L800,550 L1000,300'.
'cubic' -> 'M100,200 C100,100 250,100 250,200
                                       S400,300 400,200'.
} do: [ :each |
	| aGeometry anElement |
	aGeometry :=
		BlSvgPath new
			svgPathString: each value;
			yourself.
	anElement := aGeometry asElement
		background: Color transparent;
		border: (BlBorder paint: Color random width: 5);
		beOutskirtsCentered;
		yourself.
	aSpace root addChild: anElement ].
```
Screenshot 2023-08-23 at 14 08 20

These paths were inspired on https://www.w3.org/TR/SVG2/paths.html

Elliptical Arcs is buggy: "x axis rotation" is ignored

**Comment by tinchodias** [comment]
```smalltalk


aSpace := BlSpace new
	extent: 1100@600;
	show;
	yourself.
aSpace root background: Color black.
aSpace root layout: BlFlowLayout horizontal.
#(
0 0
0 1
1 0
1 1
) pairsDo: [ :l :s |
	| aBase aGeometry anElement |
	aBase := BlElement new clipChildren: false;
		"constraintsDo:[:c | c horizontal fitContent. c vertical fitContent ];"
		size: 300 asPoint;
	yourself.
	aBase addChild: (BlEllipseGeometry new asElement
		position: 25@75;
		size: 200@100;
		yourself).
	aBase addChild: (BlEllipseGeometry new asElement
		position: 125@25;
		size: 200@100;
		yourself).
	aSpace root addChild: aBase.
	aGeometry :=
		BlSvgPath new
			svgPathString: ('M 125,75 a100,50 0 {1},{2} 100,50' format: {l. s});
			yourself.
	anElement := aGeometry asElement
		size: 200 asPoint;
		background: Color transparent;
		border: (BlBorder paint: Color random width: 5);
		beOutskirtsCentered;
		yourself.
	aBase addChild: anElement ]
```

Screenshot 2023-08-23 at 14 10 10

Colored arcs should look like in:
image

**Comment by tinchodias** [comment]
This example seems to be okay:

```smalltalk
space := BlSpace new.
space root layout: BlLinearLayout horizontal.

BlSvgIcons iconSelectors do: [ :each |
	| result |
	result := BlSvgIcons perform: each.
	result size: 32 asPoint.
	space root addChild: result ].

space aeAsForm.
```

Screenshot 2023-08-23 at 14 14 16

**Comment by tinchodias** [comment]
@plantec @Ducasse @labordep 

In this branch, the BaselineOfBloc loads it.

This should work:
```
[ Metacello new
	baseline: 'Bloc';
	repository: 'github://pharo-graphics/Bloc:svg/src';
	onConflictUseIncoming;
	ignoreImage;
	load ]
		on: MCMergeOrLoadWarning
		do: [ :warning | warning load ]
```

**Comment by tinchodias** [comment]
Another example from SVG spec examples that seems to be okay:


Screenshot 2023-08-23 at 18 38 19


```smalltalk
aSpace := BlSpace new
	extent: 600 asPoint;
	show;
	yourself.

{
'M100,200 C100,100 400,100 400,200'.
'M100,500 C25,400  475,400 400,500'.
'M100,800 C175,700 325,700 400,800'.
'M600,200 C675,100 975,100 900,200'.
'M600,500 C600,350 900,650 900,500'.
'M600,800 C625,700 725,700 750,800 S875,900 900,800'.
} do: [ :each |
	| aGeometry anElement |
	aGeometry :=
		BlSvgPath new
			svgPathString: each value;
			yourself.
	anElement := aGeometry asElement
		background: Color transparent;
		border: (BlBorder paint: Color red width: 3);
		beOutskirtsCentered;
		transformDo: [ :t | t scaleBy: 0.5 ];
		yourself.
	aSpace root addChild: anElement ]
```

**Comment by tinchodias** [comment]
@plantec asked me if it works with ant-design-icons. It doesn't look bad (except the eye):

Screenshot 2023-08-25 at 18 49 48

```smalltalk
baseUrl := 'https://raw.githubusercontent.com/ant-design/ant-design-icons/%40ant-design/icons-svg%404.0.0/packages/icons-svg/svg/twotone/'.
files := 'account-book.svg
alert.svg
api.svg
appstore.svg
audio.svg
bank.svg
bell.svg
book.svg
box-plot.svg
bug.svg
build.svg
bulb.svg
calculator.svg
calendar.svg
camera.svg
car.svg
carry-out.svg
check-circle.svg
check-square.svg
ci-circle.svg
ci.svg
clock-circle.svg
close-circle.svg
close-square.svg
cloud.svg
code.svg
compass.svg
contacts.svg
container.svg
control.svg
copy.svg
copyright-circle.svg
copyright.svg
credit-card.svg
crown.svg
customer-service.svg
dashboard.svg
database.svg
delete.svg
diff.svg
dislike.svg
dollar-circle.svg
dollar.svg
down-circle.svg
down-square.svg
edit.svg
environment.svg
euro-circle.svg
euro.svg
exclamation-circle.svg
experiment.svg
eye-invisible.svg
eye.svg
file-add.svg
file-excel.svg
file-exclamation.svg
file-image.svg
file-markdown.svg
file-pdf.svg
file-ppt.svg
file-text.svg
file-unknown.svg
file-word.svg
file-zip.svg
file.svg
filter.svg
fire.svg
flag.svg
folder-add.svg
folder-open.svg' lines.

space := BlSpace new.
space root layout: BlFlowLayout horizontal.
elements := files collect: [ :eachName |
	| e |
	e := BlSvgConverter convertFromURL: (baseUrl, eachName).
	e size: 64 asPoint.
	space root addChild: e ].
space show
```

**Comment by tinchodias** [comment]
The classic tiger started to work too, after latest commits. 

Screenshot 2023-08-25 at 18 56 37

Open with: `BlSvgExamples new pathTiger size: 900 asPoint; openInNewSpace`

**Comment by plantec** [comment]
Cool. Excellent!!!! 
Thanks Martin

**Comment by labordep** [comment]
Thanks @tinchodias !
I will test with my SVG files :)

**Comment by tinchodias** [comment]
Let's merge it

**Comment by tinchodias** [comment]
For the record, I worked more on SVG in https://github.com/pharo-graphics/Bloc/commit/d03642ce3c968daeccbec5636a992806e735968e

**Pull request merged**
