### PR TITLE
Equality and hash

### PR DESCRIPTION
**Pull request by Nyan11**
I added Unit Test for equality on all the BlLayout (except BlInfiniteLayout).
I added missing hash functions

### CODE REVIEW

**Comment by tinchodias** [comment]
> I added Unit Test for equality on all the BlLayout (except BlInfiniteLayout). I added missing hash functions

I didn't understand the "except BlInfiniteLayout" because I the changes show a new = in that class.

I consider all = and hash added are correct. Maybe only the = in BlInfiniteLayout may be questionable, because it's not clear that comparing some instvars is necessary. I mean conceptually, e.g. the announcer sound as something secondary that may not belong to the concept of equals.

**Comment by plantec** [comment]
I would not install this PR.
Layout can have many internal states and this can lead to issues that are difficult to understand in case new state are added or new layout subclasses are added.
If one need to compare layout, one can introduce dedicated method for that.

**Comment by tinchodias** [comment]
I am not against this PR, I like when objects have a good = that is consistent with the concept the object represents. I only doubted about infinite, and I think we can fix them on evolution if issues appear...
Alain, when you say a "dedicated method" you are talking of another selector? maybe a selector that is not = but another term that is less strong in Pharo. such as "sameLayoutAs: anotherLayout"?

**Comment by Nyan11** [comment]
First i was using it in the serializer of Pyramid (https://github.com/Nyan11/Stash).
The serializer used a Dictionary to map all the objects inside a BlElement.

But i changed the Dictionnary for an IdentityDictionnary that does not required the equality and the hash method.
So i do not need this functions anymore.

**Comment by Nyan11** [comment]
I think equal is only usefull if you use the collection of Pharo. Maybe for unit testing ?

**Comment by tinchodias** [comment]
Ah, okay, I thought it was a requirement from Pyramid.
Good equals could improve performance, by avoiding triggering redundant updates. For example: https://github.com/pharo-graphics/Bloc/blob/a5fe2d3cbb74fb5d01f472191d61f0637ddf939a/src/Bloc/BlElement.class.st#L2268-L2282

and there are many places with this kind of early returns, when the new property that's being set is the same as the current one.

**Comment by plantec** [comment]
I'm strongly against this PR.
- equality is application dependent. If one application needs this feature then it can introduce a dedicated selector for it. 
- what does it mean equality of layout in Bloc ? are the caches taken into account ?
- given the complexity of a layout object, it can introduce bogues or regression in case of a new layout definition
- regarding the #layout: accessor, it is rarely used during an element lifetime, so no real optimization. in the contrary, comparing complex object can be time consuming and it could more time consuming than simply get a new instance. one should not optimize early, to not introduce useless complexity. I've removed a lot of "optimizations" in BlInfinite*

**Comment by Nyan11** [comment]
The geometries have equals methods. Should we remove them ?

**Comment by plantec** [comment]
I guess Martin introduced it.
I would remove it also. 
A geometry is not immutable and #= implies float comparison...
And it is not even used in BlElement>>#geometry:

**Pull request merged**
