### PR TITLE
Removing Sparta

### PR DESCRIPTION
**Pull request by tinchodias**
It seems to work well.  It is almost ready, for the case somebody wants to try it (@plantec).

### CODE REVIEW

**Comment by plantec** [comment]
'Hello' asRopedText asElement openInNewSpace 
leads to
BlTextElementMeasurer>>measureTextParagraph: aBlTextParagraph of: aTextElement
	self subclassResponsibility

Capture d’écran 2022-12-29 à 22 20 55

**Comment by tinchodias** [comment]
@plantec sorry, fixed now.
To write previous message, I only preformed tests without text, apparently... too bad!

**Comment by plantec** [comment]
all seem ok now. thanks.

**Comment by tinchodias** [comment]
So, merged it!

**Pull request merged**
