### PR TITLE
Remove styles

### LINKED ISSUE #398: Styles are currently mocked. Do we remove them completely?
BlElement>>styles returns nil, and the styles applying phase in the universe is not used. Toplo does not use them, right, @plantec ?

Senders of styles:
Screenshot 2024-01-15 at 18 07 13

and there are some more sender ramifications that are unused.

### PR DESCRIPTION
**Pull request by jecisc**
This change removes BLStyles and related code.

Fixes #398

Code can be found here: https://github.com/pharo-graphics/Bloc-Styles

### CODE REVIEW

**Comment by tinchodias** [comment]
Thanks @jecisc ! 
The `BlSpaceFrameStylePhase` is also part of the related code. It should be moved the toe new repo, too.

**Comment by plantec** [comment]
BlSpaceFramePropertiesPhase also is styles related

**Comment by jecisc** [comment]
I moved it too

**Comment by tinchodias** [comment]
Wow, maybe if `BlSpaceFramePropertiesPhase` is gone, all properties' classes and BlSpace API should go too... but not sure if in the same PR.

**Comment by plantec** [comment]
super!

**Comment by tinchodias** [comment]
@jecisc what do you prefer about properties? try to remove them in this same branch to have a more atomic PR or we merge this PR now and the properties removal is another PR?

**Comment by tinchodias** [comment]
The tip of the thread for the properties is `BlSpace>>doComputeProperties`... `BlSpaceFramePropertiesPhase` was the only sender... and if I understand correctly, many classes in Basic-Properties package are unreferenced now. Styles was the main user of properties... right @plantec ?

**Comment by plantec** [comment]
afaik yes.

**Comment by jecisc** [comment]
> @jecisc what do you prefer about properties? try to remove them in this same branch to have a more atomic PR or we merge this PR now and the properties removal is another PR?

I prefer to do two smaller PR :)
Like this, if there is a problem with the properties at least we will have the styles removed

**Pull request merged**
